<div id="footer"{if !$index && !$demo} class="f-common"{/if}>
    <div class="inner01 cf">
        <ul>
            <li><a href="/">{$locale.g_home}</a></li>
            <li><a href="/about">{$locale.f_about}</a></li>
            <li><a href="/privacy">{$locale.f_privacy}</a></li>
        </ul>
        <p>&copy; {$locale.copy}</p>
        <div class="fb"><iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.popapp-simulator.com%2F&amp;locale=en_US&amp;send=false&amp;layout=standard&amp;width=450&amp;show_faces=false&amp;font&amp;colorscheme=dark&amp;action=like&amp;height=35&amp;appId=450158261698811" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:35px;" allowTransparency="true"></iframe></div>
    </div>
</div>
{include file="include/common/analytics.inc"}