<div id="header">
    <div id="inner01" class="cf">
        <div class="logo"><a href="/">popApps</a></div>
        <div class="nav">
            <ul class="cf">
                {include file="include/common/signin.inc"}
                <li><a href="/">Home</a></li>
                <li><a href="#a_features">Features</a></li>
                <li><a href="#a_plans">Plans</a></li>
                <li><a href="#a_faq">FAQ</a></li>
            </ul>
        </div>
    </div>
</div>