<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="/js/flick.php" type="text/javascript"></script>
<script src="/js/iphone5.php" type="text/javascript"></script>
<link href="/css/iphone.css" rel="stylesheet" type="text/css" media="screen" />
<link href="/css/background_phone.php" rel="stylesheet" type="text/css" media="screen" />
<link href="/css/iphone5.php?d={$iphone.direction|default:0}&p={$iphone.position|default:1}{if isset($is_home)}&h={$is_home|default:1}{/if}{if isset($is_console_phone)}&c={$is_console_phone|default:1}{/if}{if isset($home_p)}&home_p={$home_p|default:2}{/if}" rel="stylesheet" type="text/css" media="screen" />