<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="/js/jquery.flickable-1.0b3-jq1.6.js" type="text/javascript"></script>
<script src="/js/iphone.js" type="text/javascript"></script>
<link href="/css/iphone.css" rel="stylesheet" type="text/css" media="all" />
<link href="/css/iphone5_{$iphone.direction|default:0}.css" rel="stylesheet" type="text/css" media="all" />
{if !$is_console}<link href="/css/frame/setting/{$iphone.direction|default:0}{$iphone.position|default:0}.css" rel="stylesheet" type="text/css" media="all" />{/if}