<div class="price">
    <p>{$locale.advance_cost}</p>
</div>
<div class="app">
    <p>{$locale.advance_feature_1}</p>
    <p>{$locale.advance_feature_2}</p>
    <p>{$locale.advance_feature_3}</p>
    {*<p>{$locale.advance_feature_4}</p>*}
</div>
<div class="bestfor">
    <p>{$locale.advance_bestfor_title}</p>
    <ul>
        <li>{$locale.advance_bestfor_1}</li>
        <li>{$locale.advance_bestfor_2}</li>
        <li>{$locale.advance_bestfor_3}</li>
    </ul>
</div>