<div class="price">
    <p>{$locale.basic_cost}</p>
</div>
<div class="app">
    <p>{$locale.basic_feature_1}</p>
    <p>{$locale.basic_feature_2}</p>
    <p>{$locale.basic_feature_3}</p>
    {*<p>{$locale.basic_feature_4}</p>*}
</div>
<div class="bestfor">
    <p>{$locale.basic_bestfor_title}</p>
    <ul>
        <li>{$locale.basic_bestfor_1}</li>
        <li>{$locale.basic_bestfor_2}</li>
    </ul>
</div>