<div id='demo2_popapps-mobile-box'><div id='demo2_up-btn'><img src='{$ssl_path}up.png' /></div><div id='demo2_down-btn'><img src='{$ssl_path}down.png' /></div></div>
<div id='demo2_popapps-frame' style='z-index: 2147483582;width:504px;height:329px;position: fixed;bottom:-329px;left: 5px;padding:0px;margin:0px;'>
    <div id="demo2_iphone">
        <div id="demo2_app">
            <div id="demo2_top-box">
                <div class="arrow_box">
                    <table>
                    <tr>
                    {if $debug}
                    <td class="logo"><img src="https://d3jpl91pxevbkh.cloudfront.net/hachione/image/upload/w_75,h_75,c_fill,r_12/v013jdlldlou2mym3pit.jpg" width="75" height="75" /></td>
                    {else}
                    <td class="logo"><img src="https://d3jpl91pxevbkh.cloudfront.net/popapps/image/upload/w_75,h_75,c_fill,r_12/xad2o2bxcx8xax1yym6r.jpg" width="75" height="75" /></td>
                    {/if}
                    <td class="appstore" align="center"><a href="https://itunes.apple.com/us/app/fruit-ninja/id362949845?mt=8" target="_blank"><img src="{$ssl_path}appstore.gif" /></a></td>
                    </tr>
                    </table>
                </div>
            </div>
            <div id="demo2_flickable">
                <ul id="demo2_flickable_ul">
                    {if $debug}
                    <li id="flick_ezioe53gidpvwxjgjmfi"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/hachione/image/upload/w_0.63/ezioe53gidpvwxjgjmfi.jpg" /></div></li>
                    <li id="flick_sjda6wd9umikyw9smiul"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/hachione/image/upload/w_0.63/sjda6wd9umikyw9smiul.jpg" /></div></li>
                    <li id="flick_umqrlkuis3vql6x6t4nj"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/hachione/image/upload/w_0.63/umqrlkuis3vql6x6t4nj.jpg" /></div></li>
                    <li id="flick_ktt4mieyjwfw4x2m8d2j"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/hachione/image/upload/w_0.63/ktt4mieyjwfw4x2m8d2j.jpg" /></div></li>
                    <li id="flick_aybbh6jdklbrf31hwkyu"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/hachione/image/upload/w_0.63/aybbh6jdklbrf31hwkyu.jpg" /></div></li>
                    {else}
                    <li id="flick_stpyts3byxrxtahwuzpx"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/popapps/image/upload/w_0.63/stpyts3byxrxtahwuzpx.jpg" /></div></li>
                    <li id="flick_nouxnn8hlq1fqjipamlq"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/popapps/image/upload/w_0.63/nouxnn8hlq1fqjipamlq.jpg" /></div></li>
                    <li id="flick_w43ipqurtys0apxqeeay"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/popapps/image/upload/w_0.63/w43ipqurtys0apxqeeay.jpg" /></div></li>
                    <li id="flick_prfiueli3p2id5gqxi8i"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/popapps/image/upload/w_0.63/prfiueli3p2id5gqxi8i.jpg" /></div></li>
                    <li id="flick_aijrvrn1vepqoyn6l0jr"><div class="block"><img src="https://d3jpl91pxevbkh.cloudfront.net/popapps/image/upload/w_0.63/aijrvrn1vepqoyn6l0jr.jpg" /></div></li>
                    {/if}

                </ul>
            </div>
            
            <div style="clear:both;"></div>
            <ul id="demo2_select_box"> 
                <li id="demo2_select_box_1"><a href="javascript:void(0);" id="demo2_select1">1</a></li>
                <li id="demo2_select_box_2"><a href="javascript:void(0);" id="demo2_select2">2</a></li>
                <li id="demo2_select_box_3"><a href="javascript:void(0);" id="demo2_select3">3</a></li>
                <li id="demo2_select_box_4"><a href="javascript:void(0);" id="demo2_select4">4</a></li>
                <li id="demo2_select_box_5"><a href="javascript:void(0);" id="demo2_select5">5</a></li>
            </ul>
        </div>
    </div>
</div>

