<div class="boxTemp box-detail detail{$iphone.direction|default:0}">
    <h3>{$locale.view_detail_title}</h3>
    <div class='info'>
        <div class='item clearfix'>
            <div class='label'>{$locale.detail_app_name}</div>
            <div class='value'>{$simulator.0.col_name}</div>
        </div>
        <div class='item clearfix'>
            <div class='label'>{$locale.detail_itunes_id}</div>
            <div class='value'>{$simulator.0.col_itunes_id}</div>
        </div>
        <div class='item clearfix'>
            <div class='label'>{$locale.detail_itunes_url}</div>
            <div class='value'>{$simulator.0.col_itunes_url}</div>
        </div>
    </div>
</div>