<div class="boxTemp box-detail">
    <h3>pop Apps Details</h3>
    <div class='info'>
        <div class='item clearfix'>
            <div class='label'>App name:</div>
            <div class='value'>{$simulator.0.col_name}</div>
        </div>
        <div class='item clearfix'>
            <div class='label'>ID</div>
            <div class='value'>{$simulator.0.col_itunes_id}</div>
        </div>
        <div class='item clearfix'>
            <div class='label'>itunes URL</div>
            <div class='value'>{$simulator.0.col_itunes_url}</div>
        </div>

    </div>
</div>